#include <iostream>
#include <string>
#include <fstream>
using namespace std;


int main() {
	/*“unidades.txt” que contiene los comercios adheridos a cada tipo de delivery. Cada registro del mismo, tiene los siguientes campos:
	tipo de delivery (1 a 4), código de unidad (ej: S1, K2, etc), nombre comercio, dirección y ciudad.*/
	ofstream archi;
	archi.open ("repartidores.txt");
	archi << "33446536" <<endl;
	archi << "PEREZ, JUAN" <<endl;
	archi << "D" <<endl;
	archi << "200" <<endl;
	archi << "SANTA FE" <<endl;
	archi << "42564789" <<endl;
	archi << "JORDAN, PAMELA" <<endl;
	archi << "D" <<endl;
	archi << "250" <<endl;
	archi << "SANTA FE" <<endl;
	archi << "36741258" <<endl;
	archi << "AYALA, PEDRO" <<endl;
	archi << "D" <<endl;
	archi << "341" <<endl;
	archi << "SANTO TOME" <<endl;
	archi << "38543727" <<endl;
	archi << "GONZALEZ, MARINA" <<endl;
	archi << "D" <<endl;
	archi << "120" <<endl;
	archi << "SANTA FE" <<endl;
	archi << "35718239" <<endl;
	archi << "GARCIA,AQULES" <<endl;
	archi << "D" <<endl;
	archi << "450" <<endl;
	archi << "SANTA FE" <<endl;
	archi << "21150303" <<endl;
	archi << "SOREIRA, PEDRO" <<endl;
	archi << "D" <<endl;
	archi << "394" <<endl;
	archi << "SANTA FE" <<endl;
	archi << "22382016" <<endl;
	archi << "JACOB, PATRICIA" <<endl;
	archi << "D" <<endl;
	archi << "680" <<endl;
	archi << "SANTO TOME" <<endl;
	archi << "20096734" <<endl;
	archi << "MONZON, KAREN" <<endl;
	archi << "D" <<endl;
	archi << "147" <<endl;
	archi << "SANTO TOME" <<endl;
	archi << "39579084" <<endl;
	archi << "ZAPATA, THIAGO" <<endl;
	archi << "D" <<endl;
	archi << "473" <<endl;
	archi << "SANTO TOME" <<endl;
	archi << "32145599" <<endl;
	archi << "VALENZUELA, RAFAEL" <<endl;
	archi << "D" <<endl;
	archi << "203" <<endl;
	archi << "SANTA FE" <<endl;
	archi << "26139979" <<endl;
	archi << "CORREA, ROSARIO" <<endl;
	archi << "D" <<endl;
	archi << "199" <<endl;
	archi << "SANTA FE" <<endl;
	archi << "32486061" <<endl;
	archi << "MOYA, JUAN" <<endl;
	archi << "D" <<endl;
	archi << "452" <<endl;
	archi << "SANTA FE" <<endl;
	archi << "23551025" <<endl;
	archi << "DIETZ, LORENA" <<endl;
	archi << "D" <<endl;
	archi << "453" <<endl;
	archi << "SANTA FE" <<endl;
	archi << "33313137" <<endl;
	archi << "RIVERO, LEANDRO" <<endl;
	archi << "D" <<endl;
	archi << "657" <<endl;
	archi << "SANTA FE" <<endl;
	archi << "32580547" <<endl;
	archi << "MEDINA, MURIEL" <<endl;
	archi << "D" <<endl;
	archi << "477" <<endl;
	archi << "SANTO TOME" <<endl;
	archi << "44981542" <<endl;
	archi << "RIVERO, ROCIO" <<endl;
	archi << "D" <<endl;
	archi << "510" <<endl;
	archi << "SANTA FE" <<endl;
	archi << "39295494" <<endl;
	archi << "MENDEZ, WALTER" <<endl;
	archi << "D" <<endl;
	archi << "411" <<endl;
	archi << "SANTA FE" <<endl;
	archi << "32257091" <<endl;
	archi << "ZARAGOZA, NOEMI" <<endl;
	archi << "D" <<endl;
	archi << "322" <<endl;
	archi << "SANTA FE" <<endl;
	archi << "34057876" <<endl;
	archi << "BALCAZA, MALENA" <<endl;
	archi << "D" <<endl;
	archi << "604" <<endl;
	archi << "SANTO TOME" <<endl;
	archi << "46860028" <<endl;
	archi << "MENDEZ, SOFIA" <<endl;
	archi << "D" <<endl;
	archi << "587" <<endl;
	archi << "SANTA FE" <<endl;
	archi.close ();

	archi.open ("unidades.txt");
	archi << "1" <<endl;
	archi << "S1" <<endl;
	archi << "DAR" <<endl;
	archi << "SAN JERONIMO 2850" <<endl;
	archi << "SANTA FE" <<endl;
	archi << "1" <<endl;
	archi << "S2" <<endl;
	archi << "KILBEL" <<endl;
	archi << "URQUIZA 3340" <<endl;
	archi << "SANTA FE" <<endl;
	archi << "1" <<endl;
	archi << "S3" <<endl;
	archi << "COTO" <<endl;
	archi << "SAN LUIS 360" <<endl;
	archi << "SANTA FE" <<endl;
	archi << "1" <<endl;
	archi << "S4" <<endl;
	archi << "EL TUNEL" <<endl;
	archi << "SUIPACHA 2550" <<endl;
	archi << "SANTA FE" <<endl;
	archi << "1" <<endl;
	archi << "S5" <<endl;
	archi << "ALVEAR" <<endl;
	archi << "SAN JERÓNIMO 3246" <<endl;
	archi << "SANTA FE" <<endl;
	archi << "2" <<endl;
	archi << "K1" <<endl;
	archi << "EL VIEJO" <<endl;
	archi << "4 DE ENERO 2581" <<endl;
	archi << "SANTA FE" <<endl;
	archi << "2" <<endl;
	archi << "K2" <<endl;
	archi << "LA ESTRELLA" <<endl;
	archi << "25 DE MAYO 3154" <<endl;
	archi << "SANTA FE" <<endl;
	archi << "2" <<endl;
	archi << "K3" <<endl;
	archi << "CANDELERO" <<endl;
	archi << "CORRIENTES 323" <<endl;
	archi << "SANTO TOME" <<endl;
	archi << "2" <<endl;
	archi << "K4" <<endl;
	archi << "MEGA" <<endl;
	archi << "SANTIAGO DEL ESTERO 1300" <<endl;
	archi << "SANTA FE" <<endl;
	archi << "2" <<endl;
	archi << "K5" <<endl;
	archi << "MAXI" <<endl;
	archi << "SAAVEDRA 645" <<endl;
	archi << "SANTA FE" <<endl;
	archi << "3" <<endl;
	archi << "R1" <<endl;
	archi << "LO DE SARA" <<endl;
	archi << "J. LOPEZ 140" <<endl;
	archi << "SANTA FE" <<endl;
	archi << "3" <<endl;
	archi << "R2" <<endl;
	archi << "MANUELA" <<endl;
	archi << "LA RIOJA 300" <<endl;
	archi << "SANTA FE" <<endl;
	archi << "3" <<endl;
	archi << "R3" <<endl;
	archi << "QUE PLATO" <<endl;
	archi << "ALBERDI 1600" <<endl;
	archi << "SANTO TOME" <<endl;
	archi << "3" <<endl;
	archi << "R4" <<endl;
	archi << "LA PACHA" <<endl;
	archi << "AV. RICHIERI 2000" <<endl;
	archi << "SANTO TOME" <<endl;
	archi << "3" <<endl;
	archi << "R5" <<endl;
	archi << "EL HORNITO" <<endl;
	archi << "AV. FREYRE 2790" <<endl;
	archi << "SANTA FE" <<endl;
	archi << "4" <<endl;
	archi << "F1" <<endl;
	archi << "SCALZO" <<endl;
	archi << "AV. FREYRE 2345" <<endl;
	archi << "SANTA FE" <<endl;
	archi << "4" <<endl;
	archi << "F2" <<endl;
	archi << "GARCIA" <<endl;
	archi << "RIVADAVIA 1840" <<endl;
	archi << "SANTA FE" <<endl;
	archi << "4" <<endl;
	archi << "F3" <<endl;
	archi << "WAGNER" <<endl;
	archi << "SUIPACHA 3248" <<endl;
	archi << "SANTA FE" <<endl;
	archi << "4" <<endl;
	archi << "F4" <<endl;
	archi << "BORDIGNON" <<endl;
	archi << "SAN LUIS 2236" <<endl;
	archi << "SANTA FE" <<endl;
	archi << "4" <<endl;
	archi << "F5" <<endl;
	archi << "CHEMES" <<endl;
	archi << "URQUIZA 2182" <<endl;
	archi << "SANTA FE" <<endl;
	archi.close ();
	
	return 0;
}

